# pubspec.yaml (твой форк horizontal_week_calendar)

name: horizontal_week_calendar
description: >
  A horizontal week calendar with on-change-week and on-date-selected callbacks.
  (Форк: совместим с intl ^0.20.2 для Flutter 3.35.x)

# Версия пакета — можешь оставить как в оригинале или увеличить патч/пререлиз,
# чтобы отличать свой форк (например, 0.0.20+smile.1). Это не обязательно,
# так как мы подключаем пакет по git (ветка/SHA), а не с pub.dev.
version: 0.0.20

homepage: https://github.com/chandabdullah/horizontal_week_calendar
# (опционально) можешь заменить на URL своего форка

environment:
  # Обновили диапазон Dart SDK под современный Flutter 3.x.
  # Если хочешь поддержать более старый Dart 2.18 — можешь вернуть нижнюю границу,
  # но для твоего проекта лучше так:
  sdk: '>=3.0.0 <4.0.0'

  # Минимальная версия Flutter — у оригинала очень широкая.
  # Можно оставить как есть; это не мешает совместимости.
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # КЛЮЧЕВОЕ изменение: этот форк теперь совместим с Flutter SDK,
  # который пинует intl 0.20.2 через flutter_localizations.
  intl: ^0.20.2

  # Как и в исходнике: слайдер используется для пролистывания дат.
  # Можно оставить текущую версию (совместима).
  carousel_slider_plus: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Можно поднять до 6.x, но не обязательно. Оставляем, чтобы не
  # создавать побочных эффектов в анализаторе исходного пакета.
  flutter_lints: ^2.0.0

# Секция flutter для пакета обычно пустая; оставляем как есть.
flutter:
